export const bookingConstants = {
  GET_BOOKING_REQUEST: 'GET_BOOKING_REQUEST',
  GET_BOOKING_SUCCESS: 'GET_BOOKING_SUCCESS',
  GET_BOOKING_FAILURE: 'GET_BOOKING_FAILURE',

  BOOKING_BY_ID_REQUEST: 'BOOKING_BY_ID_REQUEST',
  BOOKING_BY_ID_SUCCESS: 'BOOKING_BY_ID_SUCCESS',
  BOOKING_BY_ID_FAILURE: 'BOOKING_BY_ID_FAILURE',

  BOOKING_BY_USER_REQUEST: 'BOOKING_BY_USER_REQUEST',
  BOOKING_BY_USER_SUCCESS: 'BOOKING_BY_USER_SUCCESS',
  BOOKING_BY_USER_FAILURE: 'BOOKING_BY_USER_FAILURE',

  BOOKING_BY_SHIPMENT_REQUEST: 'BOOKING_BY_SHIPMENT_REQUEST',
  BOOKING_BY_SHIPMENT_SUCCESS: 'BOOKING_BY_SHIPMENT_SUCCESS',
  BOOKING_BY_SHIPMENT_FAILURE: 'BOOKING_BY_SHIPMENT_FAILURE',

  ADD_BOOKING_REQUEST: 'ADD_BOOKING_REQUEST',
  ADD_BOOKING_SUCCESS: 'ADD_BOOKING_SUCCESS',
  ADD_BOOKING_FAILURE: 'ADD_BOOKING_FAILURE',

  UPDATE_BOOKING_REQUEST: 'UPDATE_BOOKING_REQUEST',
  UPDATE_BOOKING_SUCCESS: 'UPDATE_BOOKING_SUCCESS',
  UPDATE_BOOKING_FAILURE: 'UPDATE_BOOKING_FAILURE',

  DELETE_BOOKING_REQUEST: 'DELETE_BOOKING_REQUEST',
  DELETE_BOOKING_SUCCESS: 'DELETE_BOOKING_SUCCESS',
  DELETE_BOOKING_FAILURE: 'DELETE_BOOKING_FAILURE',
};
