export const shipmentsConstants = {
  GET_SHIPMENTS_REQUEST: 'GET_SHIPMENTS_REQUEST',
  GET_SHIPMENTS_SUCCESS: 'GET_SHIPMENTS_SUCCESS',
  GET_SHIPMENTS_FAILURE: 'GET_SHIPMENTS_FAILURE',

  SHIPMENTS_BY_ID_REQUEST: 'SHIPMENTS_BY_ID_REQUEST',
  SHIPMENTS_BY_ID_SUCCESS: 'SHIPMENTS_BY_ID_SUCCESS',
  SHIPMENTS_BY_ID_FAILURE: 'SHIPMENTS_BY_ID_FAILURE',

  SHIPMENTS_BY_USER_REQUEST: 'SHIPMENTS_BY_USER_REQUEST',
  SHIPMENTS_BY_USER_SUCCESS: 'SHIPMENTS_BY_USER_SUCCESS',
  SHIPMENTS_BY_USER_FAILURE: 'SHIPMENTS_BY_USER_FAILURE',

  ADD_SHIPMENTS_REQUEST: 'ADD_SHIPMENTS_REQUEST',
  ADD_SHIPMENTS_SUCCESS: 'ADD_SHIPMENTS_SUCCESS',
  ADD_SHIPMENTS_FAILURE: 'ADD_SHIPMENTS_FAILURE',

  UPDATE_SHIPMENTS_REQUEST: 'UPDATE_SHIPMENTS_REQUEST',
  UPDATE_SHIPMENTS_SUCCESS: 'UPDATE_SHIPMENTS_SUCCESS',
  UPDATE_SHIPMENTS_FAILURE: 'UPDATE_SHIPMENTS_FAILURE',

  DELETE_SHIPMENTS_REQUEST: 'DELETE_SHIPMENTS_REQUEST',
  DELETE_SHIPMENTS_SUCCESS: 'DELETE_SHIPMENTS_SUCCESS',
  DELETE_SHIPMENTS_FAILURE: 'DELETE_SHIPMENTS_FAILURE',
};
