export const userConstants = {
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE',

  USER_BY_ID_REQUEST: 'USER_BY_ID_REQUEST',
  USER_BY_ID_SUCCESS: 'USER_BY_ID_SUCCESS',
  USER_BY_ID_FAILURE: 'USER_BY_ID_FAILURE',

  USER_BY_TYPE_REQUEST: 'USER_BY_TYPE_REQUEST',
  USER_BY_TYPE_SUCCESS: 'USER_BY_TYPE_SUCCESS',
  USER_BY_TYPE_FAILURE: 'USER_BY_TYPE_FAILURE',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  ADD_PROPIC_REQUEST: 'ADD_PROPIC_REQUEST',
  ADD_PROPIC_SUCCESS: 'ADD_PROPIC_SUCCESS',
  ADD_PROPIC_FAILURE: 'ADD_PROPIC_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_USER: 'LOGOUT_USER',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  DISABLE_ACCOUNT_REQUEST: 'DISABLE_ACCOUNT_REQUEST',
  DISABLE_ACCOUNT_SUCCESS: 'DISABLE_ACCOUNT_SUCCESS',
  DISABLE_ACCOUNT_FAILURE: 'DISABLE_ACCOUNT_FAILURE',
};
